import Foundation

/// Entry point for the app layer: enumerates available sources and builds parser instances
/// from a shared `MangaLoaderContext`. As more sources are ported, add them to `entries`.
public final class SourceCatalog: @unchecked Sendable {
    public struct Entry: Identifiable, Sendable {
        public let descriptor: MangaParserSource
        public let make: @Sendable (MangaLoaderContext) -> MangaParser
        public var id: String { descriptor.name }
    }

    public let context: MangaLoaderContext
    public let entries: [Entry]
    private var instances: [String: MangaParser] = [:]
    private let lock = NSLock()

    public init(context: MangaLoaderContext = DefaultLoaderContext()) {
        self.context = context
        self.entries = [
            // Bespoke JSON-API source — the most reliable in the catalogue.
            // Madara-template sources — full chain (list+chapters+pages) verified live.
            Entry(descriptor: MangaReadOrg.sourceDescriptor) { MangaReadOrg(context: $0) },
            Entry(descriptor: S2Manga.descriptor) { S2Manga(context: $0) },
            // MangaReader-template sources (agent live-probed end-to-end).
            Entry(descriptor: ShojoScans.descriptor) { ShojoScans(context: $0) },
            Entry(descriptor: RackusReads.descriptor) { RackusReads(context: $0) },
            Entry(descriptor: CulturedWorks.descriptor) { CulturedWorks(context: $0) },
            // Additional Madara sources (probed live; culled below by full-chain test).
            Entry(descriptor: MangaSushi.descriptor) { MangaSushi(context: $0) },
            Entry(descriptor: CoffeeManga.descriptor) { CoffeeManga(context: $0) },
            Entry(descriptor: MangaForFree.descriptor) { MangaForFree(context: $0) },
            Entry(descriptor: MangaZure.descriptor) { MangaZure(context: $0) },
            Entry(descriptor: Asq3.descriptor) { Asq3(context: $0) },
            // Dropped (chapters load but pages are JS-gated → empty reader): ManhuaPlus, Nartag.

            // ComicK — JSON API; full chain verified on the macOS test (no managed CF).
            // MangaBox template (verified: MangaBat 86 pages).
            Entry(descriptor: MangaBat.descriptor) { MangaBat(context: $0) },
            // ZeistManga template family (Blogger-based, non-CF, verified).
            Entry(descriptor: WolfScanBr.descriptor) { WolfScanBr(context: $0) },
            Entry(descriptor: Ler999.descriptor) { Ler999(context: $0) },
            // Batch 2 — more Madara/MangaReader concrete sources (full chain verified).
            Entry(descriptor: MangaDistrict.descriptor) { MangaDistrict(context: $0) },
            Entry(descriptor: MangaOwlIo.descriptor) { MangaOwlIo(context: $0) },
            Entry(descriptor: LhTranslation.descriptor) { LhTranslation(context: $0) },
            Entry(descriptor: ManhwaClub.descriptor) { ManhwaClub(context: $0) },
            Entry(descriptor: Hentai20.descriptor) { Hentai20(context: $0) },
            Entry(descriptor: ManhuaScanUs.descriptor) { ManhuaScanUs(context: $0) },
            // MadTheme template — verified working.
            Entry(descriptor: MangaJinx.descriptor) { MangaJinx(context: $0) },
            Entry(descriptor: TooniTube.descriptor) { TooniTube(context: $0) },
            // Dropped (502/dead/empty): BeeHentai, MangaPuma, MangaCute, MangaForest, MangaXyz, Toonily.Me
            // NepNep — Dropped (404, canonical @Broken): MangaSee, Manga4Life
            // FoolSlide family (non-CF, verified live).
            Entry(descriptor: DeathTollScans.descriptor) { DeathTollScans(context: $0) },
            Entry(descriptor: Mangatellers.descriptor) { Mangatellers(context: $0) },
            Entry(descriptor: MenudoFansub.descriptor) { MenudoFansub(context: $0) },
            // HeanCms family — OmegaScans verified (38 ch/11 pg).
            Entry(descriptor: OmegaScans.descriptor) { OmegaScans(context: $0) },
            // Dropped (521/404/DNS-fail): ReaperComics, TempleScan, YugenMangas
            // Liliana family — ManhuaPlus.org verified (202 ch/172 pg!).
            Entry(descriptor: ManhuaPlusOrg.descriptor) { ManhuaPlusOrg(context: $0) },
            // Dropped (timeout): MangaSect, ManhuaGold
            // Batch 4 — Madara concretes. Verified non-CF: PawManga (98pg), HiperDex (118pg),
            // MadaraDex (71pg), ManhwaTop (3869 ch). Rest CF-gated (interactive sheet).
            Entry(descriptor: PawManga.descriptor) { PawManga(context: $0) },
            Entry(descriptor: HiperDex.descriptor) { HiperDex(context: $0) },
            Entry(descriptor: MadaraDex.descriptor) { MadaraDex(context: $0) },
            Entry(descriptor: ManhwaTop.descriptor) { ManhwaTop(context: $0) },
            Entry(descriptor: KissManga.descriptor) { KissManga(context: $0) },
            Entry(descriptor: ToonGod.descriptor) { ToonGod(context: $0) },
            Entry(descriptor: DragonTea.descriptor) { DragonTea(context: $0) },
            Entry(descriptor: MangaLionz.descriptor) { MangaLionz(context: $0) },
            Entry(descriptor: MangaStarz.descriptor) { MangaStarz(context: $0) },
            // MangaReader concretes — verified live.
            Entry(descriptor: Manhwaindo.descriptor) { Manhwaindo(context: $0) },
            Entry(descriptor: Mihentai.descriptor) { Mihentai(context: $0) },
            // Keyoapp family (NEW) — KewnScans verified (26pg); NecroScans CF.
            Entry(descriptor: KewnScans.descriptor) { KewnScans(context: $0) },
            Entry(descriptor: NecroScans.descriptor) { NecroScans(context: $0) },
            // Dropped (0 pages / empty / dead): SleepyTranslations, ManhwaLatino, ManhuaScan,
            // KaliScan, WestManga, KaiScans, TecnoScann, ArvenScans, Iken family
            // (HiveComic/MagusToon/VortexScans pages broken), EzManga (404), LaidBackScans.
            // Batch 5 — Madara concretes (all probed list+chapters+pages>0; some CF).
            Entry(descriptor: Tritinia.descriptor) { Tritinia(context: $0) },
            Entry(descriptor: LilyManga.descriptor) { LilyManga(context: $0) },
            Entry(descriptor: MangaManiacs.descriptor) { MangaManiacs(context: $0) },
            Entry(descriptor: WhaleManga.descriptor) { WhaleManga(context: $0) },
            Entry(descriptor: FireScans.descriptor) { FireScans(context: $0) },
            Entry(descriptor: ShibaManga.descriptor) { ShibaManga(context: $0) },
            Entry(descriptor: InstaManhwa.descriptor) { InstaManhwa(context: $0) },
            Entry(descriptor: KlikManga.descriptor) { KlikManga(context: $0) },
            // Dropped: Manhuaplus (0 pages/JS-gated), MilfToon (admin-ajax 400).
            // Keyoapp concretes (RezoScans/Scans4u CF; SuryaScans dropped — unverified).
            Entry(descriptor: RezoScans.descriptor) { RezoScans(context: $0) },
            Entry(descriptor: Scans4u.descriptor) { Scans4u(context: $0) },
            // MangaReader concretes (verified live end-to-end).
            Entry(descriptor: StellarSaber.descriptor) { StellarSaber(context: $0) },
            Entry(descriptor: Lianscans.descriptor) { Lianscans(context: $0) },
            Entry(descriptor: Raikiscan.descriptor) { Raikiscan(context: $0) },
            Entry(descriptor: Kanzenin.descriptor) { Kanzenin(context: $0) },
            Entry(descriptor: KomikPoi.descriptor) { KomikPoi(context: $0) },
            // FoolSlide.
            Entry(descriptor: ReadNifteam.descriptor) { ReadNifteam(context: $0) },
            // Iken family (page extraction FIXED — img[data-reader-page-image]).
            Entry(descriptor: HiveComic.descriptor) { HiveComic(context: $0) },
            Entry(descriptor: MagusToon.descriptor) { MagusToon(context: $0) },
            Entry(descriptor: VortexScans.descriptor) { VortexScans(context: $0) },
            // Batch 6 — NEW template families: MMRCMS, FMReader, MangaWorld.
            Entry(descriptor: AnzMangasHd.descriptor) { AnzMangasHd(context: $0) },
            Entry(descriptor: BananaScan.descriptor) { BananaScan(context: $0) },
            Entry(descriptor: ReadComicsOnline.descriptor) { ReadComicsOnline(context: $0) },
            Entry(descriptor: Weloma.descriptor) { Weloma(context: $0) },
            Entry(descriptor: MangaWorld.descriptor) { MangaWorld(context: $0) },
            Entry(descriptor: MangaWorldAdult.descriptor) { MangaWorldAdult(context: $0) },
            // Batch 6 — Madara concretes.
            Entry(descriptor: MangaZin.descriptor) { MangaZin(context: $0) },
            Entry(descriptor: HentaixYuri.descriptor) { HentaixYuri(context: $0) },
            Entry(descriptor: Manga18x.descriptor) { Manga18x(context: $0) },
            Entry(descriptor: KsGroupScans.descriptor) { KsGroupScans(context: $0) },
            Entry(descriptor: GedeComix.descriptor) { GedeComix(context: $0) },
            Entry(descriptor: Vermanhwa.descriptor) { Vermanhwa(context: $0) },
            Entry(descriptor: MundoManhwa.descriptor) { MundoManhwa(context: $0) },
            Entry(descriptor: Manhatic.descriptor) { Manhatic(context: $0) },
            // Batch 7 — MangaThemesia concretes (same template as MangaReaderParser; live-verified).
            Entry(descriptor: MangaTxCc.descriptor) { MangaTxCc(context: $0) },
            Entry(descriptor: SushiScanFR.descriptor) { SushiScanFR(context: $0) },
            // Batch 7 — Madara concretes (full chain verified).
            Entry(descriptor: ComicsValley.descriptor) { ComicsValley(context: $0) },
            Entry(descriptor: ManhwaHub.descriptor) { ManhwaHub(context: $0) },
            // Batch 7 — MangaReader concretes (full chain verified).
            Entry(descriptor: RizzComic.descriptor) { RizzComic(context: $0) },
            Entry(descriptor: SkyManga.descriptor) { SkyManga(context: $0) },
            Entry(descriptor: KofiScans.descriptor) { KofiScans(context: $0) },
            Entry(descriptor: MangaSusuku.descriptor) { MangaSusuku(context: $0) },
            Entry(descriptor: NirvanaManga.descriptor) { NirvanaManga(context: $0) },
            Entry(descriptor: Tsundoku.descriptor) { Tsundoku(context: $0) },
            // Batch 7 dropped (files kept, unregistered): RokariComics & KomikIndo (0 pages/JS-gated),
            // UmiManga (HTTP 400 URL bug), MangaDna/Komiku (empty list), MangaDass (0 chapters),
            // AquaManga/ToonClash/YaoiHub (admin-ajax HTTP 400), PianManga (404).
            // Managed-CF sources: reachable via the interactive challenge sheet (one-time
            // human verification). The CF presentation is verified; per-source parsers are
            // NOT verified post-clearance (simctl can't tap Turnstile).
            Entry(descriptor: XoxoComics.descriptor) { XoxoComics(context: $0) },
            Entry(descriptor: NetTruyen.descriptor) { NetTruyen(context: $0) },
            Entry(descriptor: TopTruyen.descriptor) { TopTruyen(context: $0) },
            Entry(descriptor: MangaNeloCom.descriptor) { MangaNeloCom(context: $0) },
            Entry(descriptor: Mangakakalot.descriptor) { Mangakakalot(context: $0) },
            Entry(descriptor: KunManga.descriptor) { KunManga(context: $0) },
            Entry(descriptor: SetsuScans.descriptor) { SetsuScans(context: $0) },
            Entry(descriptor: Manhuafast.descriptor) { Manhuafast(context: $0) },
            Entry(descriptor: ManhwaClan.descriptor) { ManhwaClan(context: $0) },
            Entry(descriptor: WebtoonXyz.descriptor) { WebtoonXyz(context: $0) },
            // (verified XoxoComics fails in-app): WpComics family, MangaNelo, Mangakakalot,
            // KunManga, SetsuScans, Manhuafast, ManhwaClan, WebtoonXyz. Files kept, unregistered.

            // --- AUTOGENERATED BATCH ---
            Entry(descriptor: ReaperComics.descriptor) { ReaperComics(context: $0) },
            Entry(descriptor: TempleScan.descriptor) { TempleScan(context: $0) },
            Entry(descriptor: YugenMangasEs.descriptor) { YugenMangasEs(context: $0) },
            Entry(descriptor: HentaixComic.descriptor) { HentaixComic(context: $0) },
            Entry(descriptor: HentaixDickgirl.descriptor) { HentaixDickgirl(context: $0) },
            Entry(descriptor: MangaDna.descriptor) { MangaDna(context: $0) },
            Entry(descriptor: AquaManga.descriptor) { AquaManga(context: $0) },
            Entry(descriptor: ToonClash.descriptor) { ToonClash(context: $0) },
            Entry(descriptor: YaoiHub.descriptor) { YaoiHub(context: $0) },
            Entry(descriptor: PianManga.descriptor) { PianManga(context: $0) },
            Entry(descriptor: MangaDass.descriptor) { MangaDass(context: $0) },
            Entry(descriptor: SleepyTranslations.descriptor) { SleepyTranslations(context: $0) },
            Entry(descriptor: ManhwaLatino.descriptor) { ManhwaLatino(context: $0) },
            Entry(descriptor: ManhuaPlus.descriptor) { ManhuaPlus(context: $0) },
            Entry(descriptor: ArvenComics.descriptor) { ArvenComics(context: $0) },
            Entry(descriptor: Nartag.descriptor) { Nartag(context: $0) },
            Entry(descriptor: Manhuaplus.descriptor) { Manhuaplus(context: $0) },
            Entry(descriptor: MilfToon.descriptor) { MilfToon(context: $0) },
            Entry(descriptor: MangaHona.descriptor) { MangaHona(context: $0) },
            Entry(descriptor: TruyenTranhDamMyy.descriptor) { TruyenTranhDamMyy(context: $0) },
            Entry(descriptor: MangaMammy.descriptor) { MangaMammy(context: $0) },
            Entry(descriptor: FayScans.descriptor) { FayScans(context: $0) },
            Entry(descriptor: MugiwarasOficial.descriptor) { MugiwarasOficial(context: $0) },
            Entry(descriptor: ArthurScan.descriptor) { ArthurScan(context: $0) },
            Entry(descriptor: MangaLivre.descriptor) { MangaLivre(context: $0) },
            Entry(descriptor: NinjaScan.descriptor) { NinjaScan(context: $0) },
            Entry(descriptor: CrystalScan.descriptor) { CrystalScan(context: $0) },
            Entry(descriptor: YanpFansub.descriptor) { YanpFansub(context: $0) },
            Entry(descriptor: SsReading.descriptor) { SsReading(context: $0) },
            Entry(descriptor: PassamaoScan.descriptor) { PassamaoScan(context: $0) },
            Entry(descriptor: XsScan.descriptor) { XsScan(context: $0) },
            Entry(descriptor: MiniTwoScan.descriptor) { MiniTwoScan(context: $0) },
            Entry(descriptor: NirvanaScan.descriptor) { NirvanaScan(context: $0) },
            Entry(descriptor: Kalango.descriptor) { Kalango(context: $0) },
            Entry(descriptor: WonderlandScan.descriptor) { WonderlandScan(context: $0) },
            Entry(descriptor: ArcticScan.descriptor) { ArcticScan(context: $0) },
            Entry(descriptor: LimboScan.descriptor) { LimboScan(context: $0) },
            Entry(descriptor: SweetScan.descriptor) { SweetScan(context: $0) },
            Entry(descriptor: PlumaComics.descriptor) { PlumaComics(context: $0) },
            Entry(descriptor: Atemporal.descriptor) { Atemporal(context: $0) },
            Entry(descriptor: DreamScan.descriptor) { DreamScan(context: $0) },
            Entry(descriptor: HikariScan.descriptor) { HikariScan(context: $0) },
            Entry(descriptor: LekMangaCom.descriptor) { LekMangaCom(context: $0) },
            Entry(descriptor: Asq.descriptor) { Asq(context: $0) },
            Entry(descriptor: RocksManga.descriptor) { RocksManga(context: $0) },
            Entry(descriptor: Gmanga.descriptor) { Gmanga(context: $0) },
            Entry(descriptor: Olaoe.descriptor) { Olaoe(context: $0) },
            Entry(descriptor: PojokManga.descriptor) { PojokManga(context: $0) },
            Entry(descriptor: Holotoon.descriptor) { Holotoon(context: $0) },
            Entry(descriptor: Roseveil.descriptor) { Roseveil(context: $0) },
            Entry(descriptor: LumosKomik.descriptor) { LumosKomik(context: $0) },
            Entry(descriptor: Hwago.descriptor) { Hwago(context: $0) },
            Entry(descriptor: HarmonyScan.descriptor) { HarmonyScan(context: $0) },
            Entry(descriptor: PantheonScan.descriptor) { PantheonScan(context: $0) },
            Entry(descriptor: MangasOrigines.descriptor) { MangasOrigines(context: $0) },
            Entry(descriptor: MangaScantrad.descriptor) { MangaScantrad(context: $0) },
            Entry(descriptor: MhScans.descriptor) { MhScans(context: $0) },
            Entry(descriptor: TerritorioLeal.descriptor) { TerritorioLeal(context: $0) },
            Entry(descriptor: KnightnoScanlation.descriptor) { KnightnoScanlation(context: $0) },
            Entry(descriptor: HerenScan.descriptor) { HerenScan(context: $0) },
            Entry(descriptor: MangaCrab.descriptor) { MangaCrab(context: $0) },
            Entry(descriptor: MantrazScan.descriptor) { MantrazScan(context: $0) },
            Entry(descriptor: RichtoScan.descriptor) { RichtoScan(context: $0) },
            Entry(descriptor: MangaMundoDrama.descriptor) { MangaMundoDrama(context: $0) },
            Entry(descriptor: ManhwaOnline.descriptor) { ManhwaOnline(context: $0) },
            Entry(descriptor: EmperorScan.descriptor) { EmperorScan(context: $0) },
            Entry(descriptor: SapphireScan.descriptor) { SapphireScan(context: $0) },
            Entry(descriptor: MangasNoSekai.descriptor) { MangasNoSekai(context: $0) },
            Entry(descriptor: LectorManga.descriptor) { LectorManga(context: $0) },
            Entry(descriptor: BegaTranslation.descriptor) { BegaTranslation(context: $0) },
            Entry(descriptor: BarManga.descriptor) { BarManga(context: $0) },
            Entry(descriptor: Bokugents.descriptor) { Bokugents(context: $0) },
            Entry(descriptor: NoblesseTranslations.descriptor) { NoblesseTranslations(context: $0) },
            Entry(descriptor: RagnarokScanlation.descriptor) { RagnarokScanlation(context: $0) },
            Entry(descriptor: TaurusManga.descriptor) { TaurusManga(context: $0) },
            Entry(descriptor: MangaRockTeam.descriptor) { MangaRockTeam(context: $0) },
            Entry(descriptor: TopManhua.descriptor) { TopManhua(context: $0) },
            Entry(descriptor: GourmetScans.descriptor) { GourmetScans(context: $0) },
            Entry(descriptor: MangaTyrant.descriptor) { MangaTyrant(context: $0) },
            Entry(descriptor: FactManga.descriptor) { FactManga(context: $0) },
            Entry(descriptor: ManhuaManhwa.descriptor) { ManhuaManhwa(context: $0) },
            Entry(descriptor: ManhwaFull.descriptor) { ManhwaFull(context: $0) },
            Entry(descriptor: Manga1st.descriptor) { Manga1st(context: $0) },
            Entry(descriptor: MangaRolls.descriptor) { MangaRolls(context: $0) },
            Entry(descriptor: TopReadManhwa.descriptor) { TopReadManhwa(context: $0) },
            Entry(descriptor: Manhuauss.descriptor) { Manhuauss(context: $0) },
            Entry(descriptor: SectScans.descriptor) { SectScans(context: $0) },
            Entry(descriptor: WebDexScans.descriptor) { WebDexScans(context: $0) },
            Entry(descriptor: FreeMangaTop.descriptor) { FreeMangaTop(context: $0) },
            Entry(descriptor: UToon.descriptor) { UToon(context: $0) },
            Entry(descriptor: MangaFastNet.descriptor) { MangaFastNet(context: $0) },
            Entry(descriptor: ManhuaZone.descriptor) { ManhuaZone(context: $0) },
            Entry(descriptor: PhiliaScans.descriptor) { PhiliaScans(context: $0) },
            Entry(descriptor: ShootingStarScans.descriptor) { ShootingStarScans(context: $0) },
            Entry(descriptor: Manhwasco.descriptor) { Manhwasco(context: $0) },
            Entry(descriptor: ManhuaZonghe.descriptor) { ManhuaZonghe(context: $0) },
            Entry(descriptor: AsuraScansGg.descriptor) { AsuraScansGg(context: $0) },
            Entry(descriptor: SiteManga.descriptor) { SiteManga(context: $0) },
            Entry(descriptor: Zinmanga.descriptor) { Zinmanga(context: $0) },
            Entry(descriptor: JiManga.descriptor) { JiManga(context: $0) },
            Entry(descriptor: AryaScans.descriptor) { AryaScans(context: $0) },
            Entry(descriptor: Manhuaus.descriptor) { Manhuaus(context: $0) },
            Entry(descriptor: MangaRock.descriptor) { MangaRock(context: $0) },
            Entry(descriptor: ManhwaManhua.descriptor) { ManhwaManhua(context: $0) },
            Entry(descriptor: YakshaComics.descriptor) { YakshaComics(context: $0) },
            Entry(descriptor: Mangagg.descriptor) { Mangagg(context: $0) },
            Entry(descriptor: ZinMangaCom.descriptor) { ZinMangaCom(context: $0) },
            Entry(descriptor: MangaFoxFull.descriptor) { MangaFoxFull(context: $0) },
            Entry(descriptor: FreeManga.descriptor) { FreeManga(context: $0) },
            Entry(descriptor: KumaScans.descriptor) { KumaScans(context: $0) },
            Entry(descriptor: Manhuaes.descriptor) { Manhuaes(context: $0) },
            Entry(descriptor: MangaEclipse.descriptor) { MangaEclipse(context: $0) },
            Entry(descriptor: Babelwuxia.descriptor) { Babelwuxia(context: $0) },
            Entry(descriptor: MangaRead.descriptor) { MangaRead(context: $0) },
            Entry(descriptor: AsuraScansUs.descriptor) { AsuraScansUs(context: $0) },
            Entry(descriptor: MangaTxUnofficial.descriptor) { MangaTxUnofficial(context: $0) },
            Entry(descriptor: MangaTxGg.descriptor) { MangaTxGg(context: $0) },
            Entry(descriptor: Manhuaga.descriptor) { Manhuaga(context: $0) },
            Entry(descriptor: ManhwaBreakup.descriptor) { ManhwaBreakup(context: $0) },
            Entry(descriptor: TrMangaOku.descriptor) { TrMangaOku(context: $0) },
            Entry(descriptor: MangaTr.descriptor) { MangaTr(context: $0) },
            Entry(descriptor: MangaWtNet.descriptor) { MangaWtNet(context: $0) },
            Entry(descriptor: GuncelManga.descriptor) { GuncelManga(context: $0) },
            Entry(descriptor: TitanManga.descriptor) { TitanManga(context: $0) },
            Entry(descriptor: KabusManga.descriptor) { KabusManga(context: $0) },
            Entry(descriptor: TortugaCeviri.descriptor) { TortugaCeviri(context: $0) },
            Entry(descriptor: Mangawt.descriptor) { Mangawt(context: $0) },
            Entry(descriptor: Timenaight.descriptor) { Timenaight(context: $0) },
            Entry(descriptor: ArmoniScans.descriptor) { ArmoniScans(context: $0) },
            Entry(descriptor: AsuraScansTR.descriptor) { AsuraScansTR(context: $0) },
            Entry(descriptor: EzManga.descriptor) { EzManga(context: $0) },
            Entry(descriptor: LaidBackScans.descriptor) { LaidBackScans(context: $0) },
            Entry(descriptor: SuryaScans.descriptor) { SuryaScans(context: $0) },
            Entry(descriptor: RokariComics.descriptor) { RokariComics(context: $0) },
            Entry(descriptor: UmiManga.descriptor) { UmiManga(context: $0) },
            Entry(descriptor: MangaJp.descriptor) { MangaJp(context: $0) },
            Entry(descriptor: MangaMate.descriptor) { MangaMate(context: $0) },
            Entry(descriptor: PointZeroToons.descriptor) { PointZeroToons(context: $0) },
            Entry(descriptor: MangaFlame.descriptor) { MangaFlame(context: $0) },
            Entry(descriptor: AreaScans.descriptor) { AreaScans(context: $0) },
            Entry(descriptor: FlAres.descriptor) { FlAres(context: $0) },
            Entry(descriptor: Hijalacom.descriptor) { Hijalacom(context: $0) },
            Entry(descriptor: MangaAtrend.descriptor) { MangaAtrend(context: $0) },
            Entry(descriptor: ArAreaScans.descriptor) { ArAreaScans(context: $0) },
            Entry(descriptor: Manjanoon.descriptor) { Manjanoon(context: $0) },
            Entry(descriptor: Sasangeyou.descriptor) { Sasangeyou(context: $0) },
            Entry(descriptor: IzanamiScans.descriptor) { IzanamiScans(context: $0) },
            Entry(descriptor: Apkomik.descriptor) { Apkomik(context: $0) },
            Entry(descriptor: BacaKomik.descriptor) { BacaKomik(context: $0) },
            Entry(descriptor: CosmicScans.descriptor) { CosmicScans(context: $0) },
            Entry(descriptor: SoulScans.descriptor) { SoulScans(context: $0) },
            Entry(descriptor: MangakKita.descriptor) { MangakKita(context: $0) },
            Entry(descriptor: Ngomik.descriptor) { Ngomik(context: $0) },
            Entry(descriptor: Manhwaku.descriptor) { Manhwaku(context: $0) },
            Entry(descriptor: Shirakami.descriptor) { Shirakami(context: $0) },
            Entry(descriptor: KomikMama.descriptor) { KomikMama(context: $0) },
            Entry(descriptor: Noromax.descriptor) { Noromax(context: $0) },
            Entry(descriptor: Komikstation.descriptor) { Komikstation(context: $0) },
            Entry(descriptor: RimuScans.descriptor) { RimuScans(context: $0) },
            Entry(descriptor: LelManga.descriptor) { LelManga(context: $0) },
            Entry(descriptor: SushiScan.descriptor) { SushiScan(context: $0) },
            Entry(descriptor: MangasScans.descriptor) { MangasScans(context: $0) },
            Entry(descriptor: MangaTv.descriptor) { MangaTv(context: $0) },
            Entry(descriptor: MangaShiina.descriptor) { MangaShiina(context: $0) },
            Entry(descriptor: DtupScan.descriptor) { DtupScan(context: $0) },
            Entry(descriptor: AsiaLotuss.descriptor) { AsiaLotuss(context: $0) },
            Entry(descriptor: MiauScan.descriptor) { MiauScan(context: $0) },
            Entry(descriptor: EnryuManga.descriptor) { EnryuManga(context: $0) },
            Entry(descriptor: ErosScans.descriptor) { ErosScans(context: $0) },
            Entry(descriptor: WitchScans.descriptor) { WitchScans(context: $0) },
            Entry(descriptor: AstraScans.descriptor) { AstraScans(context: $0) },
            Entry(descriptor: LagoonScans.descriptor) { LagoonScans(context: $0) },
            Entry(descriptor: Nightscans.descriptor) { Nightscans(context: $0) },
            Entry(descriptor: VarnaScan.descriptor) { VarnaScan(context: $0) },
            Entry(descriptor: GreedScans.descriptor) { GreedScans(context: $0) },
            Entry(descriptor: MadaraScans.descriptor) { MadaraScans(context: $0) },
            Entry(descriptor: Readkomik.descriptor) { Readkomik(context: $0) },
            Entry(descriptor: FuryManga.descriptor) { FuryManga(context: $0) },
            Entry(descriptor: RavenScans.descriptor) { RavenScans(context: $0) },
            Entry(descriptor: XCalibrScans.descriptor) { XCalibrScans(context: $0) },
            Entry(descriptor: TecnoScans.descriptor) { TecnoScans(context: $0) },
            Entry(descriptor: MyShojo.descriptor) { MyShojo(context: $0) },
            Entry(descriptor: CypherScans.descriptor) { CypherScans(context: $0) },
            Entry(descriptor: ArenaScans.descriptor) { ArenaScans(context: $0) },
            Entry(descriptor: ManhwaFreake.descriptor) { ManhwaFreake(context: $0) },
            Entry(descriptor: SnowMachineTranslation.descriptor) { SnowMachineTranslation(context: $0) },
            Entry(descriptor: Elftoon.descriptor) { Elftoon(context: $0) },
            Entry(descriptor: PopsManga.descriptor) { PopsManga(context: $0) },
            Entry(descriptor: ReaperTrans.descriptor) { ReaperTrans(context: $0) },
            Entry(descriptor: Makimaaaaa.descriptor) { Makimaaaaa(context: $0) },
            Entry(descriptor: Manga689.descriptor) { Manga689(context: $0) },
            Entry(descriptor: MafiaManga.descriptor) { MafiaManga(context: $0) },
            Entry(descriptor: ThaiManga.descriptor) { ThaiManga(context: $0) },
            Entry(descriptor: LamiManga.descriptor) { LamiManga(context: $0) },
            Entry(descriptor: InuManga.descriptor) { InuManga(context: $0) },
            Entry(descriptor: MangaKimi.descriptor) { MangaKimi(context: $0) },
            Entry(descriptor: SereinScan.descriptor) { SereinScan(context: $0) },
            Entry(descriptor: Golgebahcesi.descriptor) { Golgebahcesi(context: $0) },
            Entry(descriptor: SummerToon.descriptor) { SummerToon(context: $0) },
            Entry(descriptor: Mangaokutr.descriptor) { Mangaokutr(context: $0) },
            Entry(descriptor: TarotScans.descriptor) { TarotScans(context: $0) },
            Entry(descriptor: ShijieScans.descriptor) { ShijieScans(context: $0) },
            Entry(descriptor: AduManga.descriptor) { AduManga(context: $0) },
            Entry(descriptor: TempestScans.descriptor) { TempestScans(context: $0) },
            Entry(descriptor: PatiManga.descriptor) { PatiManga(context: $0) },
            Entry(descriptor: ZenithScans.descriptor) { ZenithScans(context: $0) },
            Entry(descriptor: MangaKoleji.descriptor) { MangaKoleji(context: $0) },
            Entry(descriptor: MangaKings.descriptor) { MangaKings(context: $0) },
            Entry(descriptor: Gafeland.descriptor) { Gafeland(context: $0) },
            Entry(descriptor: GaiaToon.descriptor) { GaiaToon(context: $0) },
            Entry(descriptor: AthenaManga.descriptor) { AthenaManga(context: $0) },
            Entry(descriptor: Ayatoon.descriptor) { Ayatoon(context: $0) },
            Entry(descriptor: AsemiFansub.descriptor) { AsemiFansub(context: $0) },
            Entry(descriptor: Komiku.descriptor) { Komiku(context: $0) },
            Entry(descriptor: KomikIndo.descriptor) { KomikIndo(context: $0) },
            Entry(descriptor: WestManga.descriptor) { WestManga(context: $0) },
            Entry(descriptor: KaiScans.descriptor) { KaiScans(context: $0) },
            Entry(descriptor: TecnoScann.descriptor) { TecnoScann(context: $0) },
            Entry(descriptor: ArvenScans.descriptor) { ArvenScans(context: $0) },
            Entry(descriptor: GalaxScans.descriptor) { GalaxScans(context: $0) },
            Entry(descriptor: MangaSect.descriptor) { MangaSect(context: $0) },
            Entry(descriptor: ManhuaGold.descriptor) { ManhuaGold(context: $0) },
            Entry(descriptor: DocTruyen5s.descriptor) { DocTruyen5s(context: $0) },
            Entry(descriptor: Raw1001.descriptor) { Raw1001(context: $0) },
            Entry(descriptor: MangaKoma01.descriptor) { MangaKoma01(context: $0) },
            Entry(descriptor: BeeHentai.descriptor) { BeeHentai(context: $0) },
            Entry(descriptor: MangaPuma.descriptor) { MangaPuma(context: $0) },
            Entry(descriptor: MangaCute.descriptor) { MangaCute(context: $0) },
            Entry(descriptor: MangaForest.descriptor) { MangaForest(context: $0) },
            Entry(descriptor: MangaXyz.descriptor) { MangaXyz(context: $0) },
            Entry(descriptor: ToonilyMe.descriptor) { ToonilyMe(context: $0) },
            Entry(descriptor: ManhuaScan.descriptor) { ManhuaScan(context: $0) },
            Entry(descriptor: KaliScan.descriptor) { KaliScan(context: $0) },

            // --- AUTOGENERATED BATCH ---
            Entry(descriptor: Ramareader.descriptor) { Ramareader(context: $0) },
            Entry(descriptor: Deathtollscans.descriptor) { Deathtollscans(context: $0) },
            Entry(descriptor: Seinagi.descriptor) { Seinagi(context: $0) },
            Entry(descriptor: EdScanlation.descriptor) { EdScanlation(context: $0) },
            Entry(descriptor: RaiScans.descriptor) { RaiScans(context: $0) },
            Entry(descriptor: NyxScans.descriptor) { NyxScans(context: $0) },
            Entry(descriptor: Onma.descriptor) { Onma(context: $0) },
            Entry(descriptor: ScanVf.descriptor) { ScanVf(context: $0) },
            Entry(descriptor: MangaDenizi.descriptor) { MangaDenizi(context: $0) },
            Entry(descriptor: NetTruyenHE.descriptor) { NetTruyenHE(context: $0) },
            Entry(descriptor: NetTruyenVie.descriptor) { NetTruyenVie(context: $0) },
            Entry(descriptor: NewTruyen.descriptor) { NewTruyen(context: $0) },
            Entry(descriptor: DocTruyen3Q.descriptor) { DocTruyen3Q(context: $0) },
            Entry(descriptor: NhatTruyenVN.descriptor) { NhatTruyenVN(context: $0) },
            Entry(descriptor: MangaRaw.descriptor) { MangaRaw(context: $0) },
            Entry(descriptor: TyrantScans.descriptor) { TyrantScans(context: $0) },
            Entry(descriptor: DuoScanlators.descriptor) { DuoScanlators(context: $0) },
            Entry(descriptor: HeckScans.descriptor) { HeckScans(context: $0) },
            Entry(descriptor: ElevenScanlator.descriptor) { ElevenScanlator(context: $0) },
            Entry(descriptor: TemakiMangas.descriptor) { TemakiMangas(context: $0) },
            Entry(descriptor: YaoiFanClub.descriptor) { YaoiFanClub(context: $0) },
            Entry(descriptor: AnimeXNovel.descriptor) { AnimeXNovel(context: $0) },
            Entry(descriptor: RaysScan.descriptor) { RaysScan(context: $0) },
            Entry(descriptor: LonerTl.descriptor) { LonerTl(context: $0) },
            Entry(descriptor: XsanoManga.descriptor) { XsanoManga(context: $0) },
            Entry(descriptor: MangaSoul.descriptor) { MangaSoul(context: $0) },
            Entry(descriptor: MangaAiLand.descriptor) { MangaAiLand(context: $0) },
            Entry(descriptor: YokaiTeam.descriptor) { YokaiTeam(context: $0) },
            Entry(descriptor: ManhaTok.descriptor) { ManhaTok(context: $0) },
            Entry(descriptor: UlasComic.descriptor) { UlasComic(context: $0) },
            Entry(descriptor: OkyyKomik.descriptor) { OkyyKomik(context: $0) },
            Entry(descriptor: ReYume.descriptor) { ReYume(context: $0) },
            Entry(descriptor: NgamenKomik.descriptor) { NgamenKomik(context: $0) },
            Entry(descriptor: ShiyuraSub.descriptor) { ShiyuraSub(context: $0) },
            Entry(descriptor: Lepoytl.descriptor) { Lepoytl(context: $0) },
            Entry(descriptor: KomikRealm.descriptor) { KomikRealm(context: $0) },
            Entry(descriptor: DatgarScanlation.descriptor) { DatgarScanlation(context: $0) },
            Entry(descriptor: GistamisHouseFansub.descriptor) { GistamisHouseFansub(context: $0) },
        ]
        for e in entries { SourceRegistry.shared.register(e.descriptor) }
    }

    public var sources: [MangaParserSource] { entries.map(\.descriptor) }

    /// Cached parser instance for a source name (keeps cookies/config alive across calls).
    public func parser(for name: String) -> MangaParser? {
        lock.lock(); defer { lock.unlock() }
        if let cached = instances[name] { return cached }
        guard let entry = entries.first(where: { $0.descriptor.name == name }) else { return nil }
        let made = entry.make(context)
        instances[name] = made
        return made
    }
}
